{{- if eq .Values.drType "full" }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-kubeconfig
  namespace: gitops-{{ .Values.name }}
spec:
  data:
  - remoteRef:
      key: path/kubeconfigs/{{ .Values.global.clusterName }}
      property: value
    secretKey: config
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecrets.secretStore }}
  target:
    name: argocd-kubeconfig
    template:
      metadata: {}
{{- end }}
