apiVersion: v1
kind: Namespace
metadata:
  name: gitops-{{ .Values,name }}
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
  labels:
    argocd.argoproj.managed-by: gitops-{{ .Values.name }}
    {{- if eq .Values.drType "full" }}
    external-secret-label/owner: ssogroup
    {{- end }}
---
